/**
 * Rebuilds server/src/clubHistory/completedSeasons.generated.ts — the
 * pre-aggregated club figures for every COMPLETED season in
 * data/club-history (all fixtures finished). The live season is never
 * included here; the server computes it on the fly from the official API.
 * Run after a backfill, and by the weekly archive workflow (so a season
 * lands here automatically once its last fixture finishes).
 *
 *   npx tsx scripts/club-history/build-aggregates.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { aggregateClubSeason } from "../../server/src/clubHistory/aggregate.js";
import { listSeasonFolders, readSeasonLedger, seasonFromFolderName } from "../../server/src/clubHistory/ledgerFiles.js";
import type { ClubSeason } from "../../server/src/clubHistory/types.js";

const ROOT = join(process.cwd(), "data", "club-history");
const OUT = join(process.cwd(), "server", "src", "clubHistory", "completedSeasons.generated.ts");

const all: ClubSeason[] = [];
for (const folder of listSeasonFolders(ROOT)) {
  const ledger = readSeasonLedger(ROOT, seasonFromFolderName(folder));
  if (!ledger) continue;
  const clubs = aggregateClubSeason(ledger.season, ledger.teams, ledger.fixtures, ledger.rows);
  const complete = clubs.length > 0 && clubs.every((c) => c.complete);
  console.log(`${ledger.season}: ${complete ? `complete, ${clubs.length} clubs` : "in progress — skipped"}`);
  if (complete) all.push(...clubs);
}

// Stored as a JSON string literal rather than a giant object literal — a
// few hundred KB of typed literal would slow every type-check of the server.
const json = JSON.stringify(all);
writeFileSync(
  OUT,
  `// GENERATED by scripts/club-history/build-aggregates.ts from data/club-history — do not edit by hand.\n` +
    `import type { ClubSeason } from "./types.js";\n\n` +
    `export const COMPLETED_CLUB_SEASONS: ClubSeason[] = JSON.parse(${JSON.stringify(json)});\n`,
);
console.log(`Wrote ${all.length} club-seasons (${(json.length / 1024).toFixed(0)} KB) to ${OUT}`);
